title:            Cooper's Blog
description:       Blog
mywords:          A Front-End Engineer
url:              #
signoff:          Cooper
duoshuo_shortname: huguobo
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

email:  huguobo2010@126.com
github:  https://github.com/huguobo
psite:  #
weibo:  http://weibo.com/CooberHu
douban:  #

links:
  - name:         About
    url:         /about
  - name:         Home
    url:          /index.html
  - name:         List
    url:         /list
  - name:         GitHub
    url:          https://github.com/huguobo
    external:     true
  - name:         Subscibe
    url:         /feed.xml
    external:     true
  - name:         CV
    url:          https://huguobo.github.io/myResume
    external:     true
excerpt_separator:  "\n\n\n\n"
gems:           [jekyll-paginate]
paginate:         5
paginate_path:   "page:num"
permalink:        pretty
markdown:         kramdown
highlight:        pygments
