title:            Cooper's Blog
description:       Blog
mywords:          A Stupid Front-End Engineer
url:              http://huguobo.github.io
signoff:          Cooper
duoshuo_shortname: huguobo
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

email:  huguobo2010@126.com
github:  http://github.com/huguobo
psite:  http://huguobo.cn
weibo:  http://weibo.com/CooberHu
douban:  #

links:
  - name:         About
    url:          /about
  - name:         Home
    url:         /index.html
  - name:         List
    url:         /list
  - name:         Hgb's corner
    url:          http://www.huguobo.cn
    external:     true
  - name:         GitHub
    url:          http://github.com/huguobo
    external:     true
  - name:         Subscibe
    url:         /feed.xml
    external:     true
  - name:         CV
    url:          http://huguobo.github.io/myResume
    external:     true 
excerpt_separator:  "\n\n\n\n"
gems:           [jekyll-paginate]
paginate:         5
paginate_path:   "page:num"
permalink:        pretty
markdown:         redcarpet
highlight:        pygments
redcarpet:
  extensions:
    - smart
