title:            Cooper's Blog
description:      Blog
mywords:          日拱一卒，功不唐捐
url:               #
signoff:          Cooper
duoshuo_shortname: huguobo
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
links:
  - name:         About
    url:          /about
  - name:         Home
    url:         /index.html
  - name:         Hgb's corner
    url:          http://www.huguobo.cn
    external:     true
  - name:         GitHub
    url:          http://github.com/huguobo
    external:     true
  - name:         Subscibe
    url:         /feed.xml
    external:     true
  - name:         CV
    url:          http://huguobo.github.io/myResume
    external:     true
    
gems:           [jekyll-paginate]
paginate:         15
paginate_path:   "page:num"
permalink:        pretty
markdown:         redcarpet
highlight:        pygments
redcarpet:
  extensions:
    - smart
